## Arrays con NumPy - Parte II

## Numeros aleatorios

In [4]:
import numpy as np

In [2]:
# Funcion rand()

In [5]:
np.random.rand?

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      builtin_function_or_method


In [6]:
indicadores = np.random.rand(5)

In [7]:
indicadores

array([0.30082897, 0.10641343, 0.96807627, 0.23769918, 0.85593961])

In [8]:
indicadores.shape

(5,)

In [11]:
indicadores2 = np.random.rand(7,5)

In [12]:
indicadores2

array([[0.18767501, 0.29452246, 0.26956446, 0.98612627, 0.81242215],
       [0.72480023, 0.03118598, 0.11346073, 0.92849702, 0.56124954],
       [0.39341508, 0.54921539, 0.23818863, 0.77083707, 0.88779642],
       [0.89883903, 0.59589406, 0.96168399, 0.27345949, 0.54525041],
       [0.39515588, 0.92606979, 0.02789006, 0.61256927, 0.38788923],
       [0.79933002, 0.02813034, 0.20407979, 0.48202705, 0.55032782],
       [0.18539319, 0.59674047, 0.22033831, 0.45577158, 0.60664128]])

## Funciones de ndarray

In [13]:
indicadores2.min()

0.02789006231442337

In [14]:
indi_min = indicadores2.min()

In [15]:
indicadores2 == indi_min

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [16]:
indicadores2.max()

0.9861262741613093

In [17]:
ind_max = indicadores2.max()

In [18]:
indicadores2 == ind_max

array([[False, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [19]:
indicadores2.sum()

17.502437503505874

In [20]:
indicadores2.sort()

In [21]:
indicadores2

array([[0.18767501, 0.26956446, 0.29452246, 0.81242215, 0.98612627],
       [0.03118598, 0.11346073, 0.56124954, 0.72480023, 0.92849702],
       [0.23818863, 0.39341508, 0.54921539, 0.77083707, 0.88779642],
       [0.27345949, 0.54525041, 0.59589406, 0.89883903, 0.96168399],
       [0.02789006, 0.38788923, 0.39515588, 0.61256927, 0.92606979],
       [0.02813034, 0.20407979, 0.48202705, 0.55032782, 0.79933002],
       [0.18539319, 0.22033831, 0.45577158, 0.59674047, 0.60664128]])

## Funcion randint()

In [22]:
np.random.randint(1,100, 15)

array([68, 89, 84, 84, 47, 56, 61,  3, 80, 90, 64, 14, 37, 11, 58])

In [23]:
np.random.randint(1,100, size = (5,4))

array([[61,  6, 67,  2],
       [39, 18, 24, 41],
       [32, 77, 44, 12],
       [28, 42, 13, 73],
       [95, 90, 47, 91]])

In [26]:
temperaturas = np.random.randint(10,30, size = (4,7))

In [27]:
temperaturas

array([[15, 29, 10, 25, 10, 25, 26],
       [11, 19, 19, 14, 11, 27, 25],
       [15, 25, 28, 25, 17, 14, 23],
       [27, 26, 22, 22, 15, 17, 13]])

In [29]:
temperaturas2 = np.random.rand(4,7)

In [30]:
temperaturas2

array([[0.45986039, 0.11968827, 0.37263264, 0.50517876, 0.13319302,
        0.46275263, 0.50457218],
       [0.43685085, 0.38369647, 0.82302408, 0.2820993 , 0.86514048,
        0.09770901, 0.03373045],
       [0.42099934, 0.35814277, 0.19634079, 0.92043517, 0.23172951,
        0.5668076 , 0.5553301 ],
       [0.99134581, 0.49994155, 0.53628879, 0.83615165, 0.14951902,
        0.43069534, 0.01661249]])

In [31]:
temperaturas2.shape

(4, 7)

In [32]:
temps = temperaturas + temperaturas2

In [33]:
temps

array([[15.45986039, 29.11968827, 10.37263264, 25.50517876, 10.13319302,
        25.46275263, 26.50457218],
       [11.43685085, 19.38369647, 19.82302408, 14.2820993 , 11.86514048,
        27.09770901, 25.03373045],
       [15.42099934, 25.35814277, 28.19634079, 25.92043517, 17.23172951,
        14.5668076 , 23.5553301 ],
       [27.99134581, 26.49994155, 22.53628879, 22.83615165, 15.14951902,
        17.43069534, 13.01661249]])